---
  wireguard_PersistentKeepalive: 0
  wireguard_server_public_address: '87.128.11.69'
  wireguard_config_path: '/var/wireguard/configs/{{ inventory_hostname }}'
  wireguard_pki_path: "{{ wireguard_config_path }}/pki"
  wireguard_activeUser_lockfile_path: "{{ wireguard_config_path }}/active-user"
  wireguard_deletedUser_lockfile_path: "{{ wireguard_config_path }}/deleted-user"
  wireguard_interface: wg0
  wireguard_port_avoid: 53
  wireguard_port: 51822
  wireguard_server_ip: 10.100.40.1/22
  wireguard_network_ipv4: 10.100.40.0/22
  wireguard_dns_servers: 10.100.4.52,10.100.0.52
  wireguard_server_pb_key: OR/LYyOLQnt3eIjcLi7pEodR9tq510fRH14WdgD2cS0=
  wireguard_server_pv_key: wL5/DuXr0LDOjjGDeBkJbohVDLlge/qu3Fq6z3iYP20=
  wireguard_allowed_ips: 10.100.0.0/16, 176.9.202.169/32, 138.201.43.66/32, 217.151.152.162/32
  wireguard_local_config_path: "{{ role_path }}/files/{{ inventory_hostname }}"
  users:
    - john
    - armin
    - jack